#!/bin/sh
# Generated by isoloom from isoloom.yml. Don't edit: change isoloom.yml and run
# `isoloom generate`. `isoloom check` fails when this file is out of date.
# Prints the module's outputs as JSON (what `isoloom test` and the message read).
# The services of `awsgoat-module-1`: the Terraform module `app/modules/module-1`, in the user's aws account.
set -eu
cd "$(dirname "$0")"
here="$(pwd)"
export TF_DATA_DIR="$here/.terraform"
module='../../app/modules/module-1'
terraform -chdir="$module" output -json -state="$here/terraform.tfstate"
